name: PlayerTrollGUI
version: '${project.version}'
main: me.oscarcusick.playertrollgui.PlayerTrollGUI
api-version: '1.20'
commands:
  TrollGUI:
    description: "Troll the fuck out of players"
    permission: op
    permission-message: "You have to be an operator to troll"
